"
" File:         vimrc
" Author:       Markus Hoofe <mhoofe@gmail.com>
"
" Description:  Custom vim settings
"

" set delete key correctly
if $TERM >= "xterm" || $TERM == "kvt" || $TERM == "dtterm"

    set t_md=
    set t_Co=8

    " set these for newer terminals (konsole,kvt)
"    set t_kb=
"    set t_kD=[3~
"    set t_kh=[H
"    set t_@7=[F
"    set t_K1=[1~
"    set t_K4=[4~

    " set these for old xterms
    "set t_kb=
    "set t_kD=
    "set t_kh=[1~
    "set t_@7=[4~

    "set t_Sf=[3%dm
    "set t_Sb=[4%dm
    "set t_Sf=[3%p1%dm
    "set t_Sb=[4%p1%dm

endif

if $TERM == "vt220"

    set t_md=
    set t_Co=8

"    set t_kb=
"    set t_kD=
"    set t_kh=[1~
"    set t_@7=[4~

"    set t_Sf=[3%dm
"    set t_Sb=[4%dm
    "set t_Sf=[3%p1%dm
    "set t_Sb=[4%p1%dm

endif

" we want external terminal definition
"set notbi
"set term=$TERM


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Now some more or less useful options:
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" normal indenting
"set autoindent

" automatically write changes
set autowrite

" backspace behaviour (0: normal, 1: delete over EOL, 2: always delete)
set backspace=2

" enable C program indenting
set cindent

" some nice cryptic settings about c-indenting
" set cinoptions=g.5sh.5s:.5st0(0
set cinoptions=t0(0

" ring the bell for error messages
set errorbells

" disable function keys in insert/replace mode
" set noesckeys

" set modified files hidden when switching to other file(s)
"set hidden

" highlight all searchresults (see mapping)
set hlsearch

" ignore case in search patterns
set ignorecase

" immediately show the matched string for current search pattern
set incsearch

" set vim in insert mode as a default
"set insertmode

" adapt case for completion in insert mode
"set infercase

" the type of status line (0: never, 1: if at least 2 windows, 2: always)
set laststatus=2

" dont redraw screen for macros, registers and commands
set lazyredraw

" show linenumbers (see mapping)
"set number

" show position of cursor
set ruler

" how many lines to keep above and below cursor when scrolling
set scrolloff=2

" avoid trojan-horses, dont allow certain commands from within files
set secure

" shell to start with !
"set shell=sh

" number of spaces to use for each step of indent
set shiftwidth=4

" show short messages after commands and at start
"set shortmess=a

" truncate file message at start
set shortmess=t

" character to show if line was wrapped
set showbreak=>

" show matching brackets
set showmatch

" show current mode
set showmode

" number of columns to scroll horizontally when wrap is off
set sidescroll=10

" override ignorecase if search patterns contains upper case characters
set smartcase

" smarter indenting (detects ´{´ and some keywords)
set smartindent

" in front of a line <Tab> inserts ´shiftwidth´ positions
set smarttab

" number of spaces that <Tab> counts for, using a mix of tabs and spaces
set softtabstop=4

" expand tabs to spaces
set expandtab

" set number of spaces a tab counts for
set tabstop=4

" dont move the cursor to start of line when indenting with ´<<´, CTRL-T, etc.
set nostartofline

" show program title and filename in window title
set title

" set timeout on mappings
set ttimeout

" search external termcaps before builtin ones
"set nottybuiltin

" set verbosity level (0 to 9)
"set verbose=1

" use visual bell instead of beeping
set visualbell

" allow specific keys that move left/right to wrap the prev/next line
set whichwrap=b,s

" set wrapping off (see mapping)
"set nowrap


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Now for some more or less useful autocommands:
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" automagically uncompress gzipp'ed files
autocmd BufReadPre  *.gz set bin
autocmd BufReadPost *.gz '[,']!gunzip
autocmd BufReadPost *.gz set nobin

" we want linenumbers for C, C++ and java
"autocmd BufEnter    *.[ch]  set number
"autocmd BufEnter    *.[CH]  set number
"autocmd BufEnter    *.cc    set number
"autocmd BufEnter    *.hh    set number
"autocmd BufEnter    *.cpp   set number
"autocmd BufEnter    *.java  set number


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Now some more or less useful mappings:
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" make  work in insert mode
imap  

" map Meta-Pos1 to jump to beginning of line, Pos1 to jump to first character in line
map <Home> ^
map <kHome> ^
imap <Home> ^
imap <kHome> ^
map <Esc><Home> 0
imap <Esc><Home> 0

" to satisfy stupid SuSE
map <Esc>[H ^
imap <Esc>[H ^

" map Meta-Pageup to jump to beginning of file, Meta-PageDown to jump to end
map <Esc>< gg
map <Esc>> G

" map BS to delete left character in command mode
map <BS> X

" map Special(c) control left/right to word left/right
""" map <Esc>[C w
""" map <Esc>[D b
"map <Esc>OC W
"map <Esc>OD B
"imap <Esc>[C w
"imap <Esc>OC W
"imap <Esc>[D b
"imap <Esc>OD B
"imap <Esc>f W
"imap <Esc>F w
"imap <Esc>b B
"imap <Esc>B b

" map ALT-1 to CTRL-^ (so i can "do it" under windows)
"map <Esc>1 
"imap <Esc>1 

" map F5 to toggle wrapping
map <F5> :set wrap!<Bar>echo "Wrapping is " strpart("OffOn", 3 * &wrap, 3)<CR>

" map F7 to toggle search highlighting
map <F7> :set hls!<Bar>echo "HLsearching is " strpart("OffOn", 3 * &hls, 3)<CR>

" map F9 to toggle linenumbering
map <F9> :set number!<CR>

" map F10 to toggle syntax highlighting
map <F10> :if has("syntax_items")<Bar>syntax off<Bar>else<Bar>syntax on<Bar>endif<CR>


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Now for the syntax highlighting (tm):
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" turn on syntax highlighting
syntax on

hi Cursor ctermfg=Black ctermbg=Red

hi Comment ctermfg=DarkRed guifg=DarkRed

hi Constant ctermfg=DarkMagenta guifg=DarkMagenta
hi Character ctermfg=DarkGreen guifg=DarkGreen
hi String ctermfg=DarkGreen guifg=DarkGreen

hi Identifier ctermfg=Yellow
"hi Function ctermfg=Brown

hi Statement ctermfg=DarkBlue guifg=DarkBlue
hi Keyword ctermfg=DarkBlue guifg=DarkBlue

"hi PreProc cterm=italic

hi Type ctermfg=Blue guifg=DarkBlue
hi Special ctermfg=DarkMagenta guifg=DarkMagenta

hi Error ctermfg=White ctermbg=Red guifg=White guibg=Red

hi Search term=reverse ctermbg=3


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Additional stuff
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

